name: Export Godot HTML5 Game to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Godot 4
        uses: actions/setup-godot@v2
        with:
          godot-version: 4.0

      - name: Export HTML5 game
        run: |
          docker run --rm -it -v $GITHUB_WORKSPACE:/workspace barichello/godot-ci:latest godot --export html5

      - name: Deploy to GitHub Pages
        uses: actions/deploy-to-github-pages@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-branch: gh-pages
          publish-dir: ./build_html5
          folder-name: game
