name: Export Godot HTML5 Game to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Export HTML5 game
        run: |
          docker run --rm -it -v $GITHUB_WORKSPACE:/workspace barichello/godot-ci:latest godot --export html5
